### ISSUE TITLE
Documentation review / re-structure

### ISSUE THREAD

**Issue by SYNchroACK** [Intevation/intelmq-fody#14]
Hi folks,

I would like to start testing this repo to understand the possibilities to use to other interfaces related to intelmq. I check the documentation but for me (don't have any experience with the stuff that you guys are using) is not trivial to have a proof-of-concept installed on a VM. Let me know if you guys have plans to review / re-structure the installation process AKA "Installation for Dummies like me"

**Comment by bernhardreiter** [comment]
@SYNchroACK 
We are here to help, thanks for checking out fody. 
Here is the overview again what you want to do to get fody working (currently).
As fody right now can only display events for emails that have been send out with a ticket,
in order to fully see it working you need to

1. You need an intelmq installation from the certbund-branch.
2. With intelmq-mailgen setup.

For both you can follow the instructions in https://github.com/Intevation/intelmq-mailgen
(and leave out the OpenPGP part). While these instructions are complete, they take quite
a number of steps to follow.

3. You can run the intelmq-mailgen/extras/checkticket-spa/checkticket.py "serving" script
and get access to an api like ``http://localhost:8000/getLastTicketNumber`` and
``http://localhost:8000/getEventIDsForTicket``
4. You build a static javascript version of fody following the instructions and serve this from the same server as checkticket.py or run ``yarn run dev`` for a development server

There are other possibilities:
 * You give us access to a virtual machine (e.g. Ubuntu 14.04) and we set it all up.
 * We meet on IRC or XMPP and walk you through it.

**Comment by bernhardreiter** [comment]
@SYNchroACK just to be sure: You can use an Ubuntu 14.04 virtual machine with only the `devel` section from https://github.com/Intevation/intelmq-fody/blob/master/docs/SetupExampleUbuntu.md and run 
```sh
yarn
yarn run dev
```
to see the client side app working (but of course without data unless you also setup an intelmq with certbund-contact on the same machine).

**Comment by bernhardreiter** [comment]
@SYNchroACK because it is a while ago, I consider this question answere. Please feel free to contact me if you have further questions.
